version: '3'

vars:
  POSTGRES_CONTAINER_NAME: 'alafi-postgres'
  POSTGRES_VOLUME_NAME: 'pgdata'

env:
  ALAFI_CONFIG_FILE_PATH: .config.yaml

tasks:
  postgres:start:
    desc: Starts the Postgres container
    cmds:
      - docker run --name {{.POSTGRES_CONTAINER_NAME}}
        -p 5432:5432
        -v {{.POSTGRES_VOLUME_NAME}}:/var/lib/postgresql/data
        -e POSTGRES_PASSWORD=password
        -d postgres
      - while ! docker exec {{.POSTGRES_CONTAINER_NAME}} pg_isready -U postgres; do sleep 1; done
    status:
      - docker ps | grep {{.POSTGRES_CONTAINER_NAME}}

  postgres:stop:
    desc: Stops the Postgres container
    cmds:
      - docker stop {{.POSTGRES_CONTAINER_NAME}}
      - docker rm {{.POSTGRES_CONTAINER_NAME}}

  postgres:clean:
    desc: Remove the Postgres volume
    cmds:
      - docker volume rm {{.POSTGRES_VOLUME_NAME}}

  migrate:
    desc: Migrates the database
    deps:
      - postgres:start
    cmds:
      - defer: { task: postgres:stop }
      - ./manage.py migrate

  serve:
    desc: Runs the server
    deps:
      - postgres:start
    cmds:
      - defer: { task: postgres:stop }
      - ./manage.py runserver