version: '3'

vars:
  CONTAINER: 'alafi-postgres'
  VOLUME: 'pgdata'

env:
  ALAFI_CONFIG_FILE_PATH: .config.yaml

tasks:
  postgres:start:
    desc: Starts the Postgres container
    cmds:
      - docker run --name {{.CONTAINER}}
        -p 5432:5432
        -v {{.VOLUME}}:/var/lib/postgresql/data
        -e POSTGRES_PASSWORD=password
        -d postgres
      - while ! docker exec {{.CONTAINER}} pg_isready -U postgres; do sleep 1; done
    status:
      - docker ps | grep {{.CONTAINER}}

  postgres:stop:
    desc: Stops the Postgres container
    cmds:
      - docker stop {{.CONTAINER}}
      - docker rm {{.CONTAINER}}

  postgres:clean:
    desc: Remove the Postgres volume
    cmds:
      - docker volume rm {{.VOLUME}}

  shell:
    desc: Opens the Django shell
    deps:
      - postgres:start
    cmds:
      - ./manage.py shell -i ipython

  serve:
    desc: Runs the server
    deps:
      - postgres:start
    cmds:
      - ./manage.py migrate
      - ./manage.py runserver

  settle:
    desc: Run transactions settler
    deps:
      - postgres:start
    cmds:
      - ./manage.py run_transaction_settler

  test:
    desc: Runs the tests
    cmds:
      - task: postgres:start
        vars:
          CONTAINER: 'alafi-postgres-test'
          VOLUME: 'pgdata-test'
      - defer:
          task: postgres:stop
          vars:
            CONTAINER: 'alafi-postgres-test'
            VOLUME: 'pgdata-test'
      - defer:
          task: postgres:clean
          vars:
            CONTAINER: 'alafi-postgres-test'
            VOLUME: 'pgdata-test'
      - ./manage.py test